language: java
sudo: false
deploy:
  provider: releases
  file: build/libs/xlr-orson-plugin-1.0.0-beta.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-orson-plugin
  api_key:
    secure: wlsl8fyCKtMEgynD8UVgEZWSsD+URxHyMM6EOVVaDG9mec84++OCeDmKBCIHYomv/UuygF0MyT2C1EvyZIYxoDdVdJegVBpVBLhkyqyX05TVNjqxq4mZOAR3lm1yq1tQsqQBB+Q7tss40vKz4INgHtQmIwDmcSOJtuOfyhLXBtIkqNiETtLIATZuGbEvyjZ+lTg9vLaf8fvdgvImU3asHexqaoXEhuvl+glmhFzmU4Q+LkVbHLAXTpe6QtSl+fBZnZp4voFFYwwOmxi1cRDOhwkeJwV+kziTflZYSYwaRSYWvCgEwj8Pji1t7bYYCr/R5QFyg//iQ0A5ziwzffPFPc41Q1xXKFBXj9qnrzMVZEIfM7c5cJrZPf8TdtnPV9vpCbjVXgKuvlRA+3FmLy7TQ8YqPSVBouto7zPKKUB0Ns3Ai2oLfXBJ0RHckQA6QhJLNqvyk+ezSRunUf7hrj1FFg7rmDmFpsPh4h4LMZrSz8CvDDOn0aDxB+JKERSSD6mY6Ddxl5Cz99dve8Tym3Duvf4YAvXqi/6ayIfpm3z4f6g7N+GEVIH/bBt1jRTGU09GUC8jXDVRWLYWuEpS/xQGWJViWMP83dFti/xkMyqPeQAQiGqtdTMWUt4YkgX1p7lv5SFVyJ0Mn05j06S2Zs7KudlSZlPCEaD/aKeM2nQ3nuk=
notifications:
  hipchat:
    rooms:
      secure: 4MBog+gCUuCGDuEiK0/EMSdy2rj8Dep/WPj/EBTHDqF/uHHF98zF/83HCX5bSNoTXql7ACSq1EthLITZAofia2J0eGqr+NzQ2uAIOKqchB3C+2fVBSvrVSEdfunt929by6QQTEwE/I3GWz292E5WRyAIsD6I19zG8Af8XCrQkMwbNFnq+0EWGe3yxv3nlOBdlknQf4xrZHrhUmuxUMTgijcFd8NaSCXUExyS7s93P/Kzxj+x7vYY02XklqrhuRwySOKdpSOa4xJt/WRYeLDQvyl4F+/jcTLTUS1qh9hV0wThZZFEi2wFb8kM6Xvz3w8UdOqEHCoRjUotNV2qEv+pbwnQxCIlJ7wJVRw+Iaw6s0Dg54GoDeySPBBUje8uF7sfEDRreuAo1G97qwAPKov+7Cn7Uh1qD3/B2jC8l2HRse+cSRJOxd4aSuOvhZz+VExaidvH2nDEOYiM5VOIWslvwjHmViiYNaKIkBD0leJqPup8tFpJIkeeHWlRAyNhZWX3z+nG5yEhnn1Y3thUHL0KxkGdJs3mGLifJiSgHP3G99fyFnYyG/Hhy8SBj8yE8cqRaa7oX0HzZapWetcGymF7nB8Wj8mDrUpqYEF+Q/Shh0YumZA05xp7K1kvusRUcD3aV24MfwF2dzu4RLkpfmrGk9CoKXNQZ6NtovyTUih9y8Y=
